Pershendetje prof Dashamir dhe anetare te grupit te punes per Digital-safe.
Jam Suela Xamaxa,(user name varaziu eshte i familjes).
Komitin  qe zhvilova pak me pare e bera duke studiuar Dropbox-in,[https://play.google.com/store/apps/details?id=com.dropbox.android]
Kam pa fund ide per projektimin e softit tone,por kam pak kohe ne dispozicjon.Neser ne seminar dua ti diskutojme disa kerkesa te perdoruesve.
